### ISSUE TITLE
FindOpenCL: CMake 3.1.0+

### ISSUE THREAD

**Issue by ax3l** [mpicbg-scicomp/gearshifft#104]
Hi,

the current `FindOpenCL.cmake` module you ship is unfortunately not very flexible since it finds its *nix dependencies via `try_compile` rather then checking the lib and include paths.

[Since CMake 3.1.0](https://github.com/Kitware/CMake/commit/041485bc163c69e5eb2829bc78857a958cad7e87#diff-8f2a478201f50fd0b22caef61b782717), an official `FindOpenCL` Module is shipped with CMake, so you can just raise your CMake requirement and remove your script as noted in your `todo` in its header.

This issue prevents that the OpenCL backends of gearshifft can be build in https://github.com/LLNL/spack/pull/4560

**Comment by tdd11235813** [comment]
ok, thanks for reporting and the fix. The cmake 3.1.0 will be used in an upcoming PR as you recommended.

**Comment by tdd11235813** [comment]
try out if cmake3.1 resolves the build problems.

**Comment by ax3l** [comment]
@tdd11235813 thanks, the `FindOpenCL` works now as expected!

There is only an issue left with the `FindclFFT.cmake` script - can you please make sure it react properly on hints on the list of paths in the environment variable `CMAKE_PREFIX_PATH` instead (or on top) of the (deprecated) `_ROOT` environment vars?

**Comment by ax3l** [comment]
Here is a module of ours that reacts on both the recommended `CMAKE_PREFIX_PATH` environment hints as well as a (deprecated) `_ROOT` environment hint: https://github.com/ComputationalRadiationPhysics/cmake-modules/blob/dev/FindSplash.cmake

(its not the most modern script but shows how to interact with `find_path` and `find_library` in order to do disturb the default behavior)

**Comment by tdd11235813** [comment]
updated the cmake file with the file from clfft repository. 
cmake on our HPC cluster Taurus now requires
```
cmake -DCLFFT_ROOT=$CLFFT_ROOT ..
```

**Comment by ax3l** [comment]
Yes, but ideally a bash export of the form
```bash
export CMAKE_PREFIX_PATH=$CLFFT_ROOT:$CMAKE_PREFIX_PATH

cmake ..
```

should be sufficient, too.

I think you should not use the `HINTS` option in `find_path` but only `PATHS` / `PATHS ENV` for hints. Also, avoid adding hard-coded system paths such as `/usr/local/`. That allows commands such as `find_library` to find libs in a more flexible way since it does not alter its default search paths (such as figuring `lib/` and `lib64/` out for us by itself).

**Comment by tdd11235813** [comment]
oh yes, you are right, `CMAKE_PREFIX_PATH` is the recommended way to point to the paths as it does not rely on lib-specific cmake variables. I provide an update. Thank you for your help again! :)
On a local system I use now:
```
export CMAKE_PREFIX_PATH=~/software/clFFT-cuda8.0-gcc5.4/:/opt/cuda:$CMAKE_PREFIX_PATH
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 ..
```

**Comment by ax3l** [comment]
fantastic, that's it! ✨ 
works like a charm, awesome!

please ping we when you draft the next release so we can add the version's sha to spack :)
