### ISSUE TITLE
decouple results from gearshifft

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft#105]
it is probably better to separate the result files from gearshifft. As we have an evaluation tool (rshiny) now, we can create a dedicated project, e.g. `mpicbg-scicomp/gearshifft_results`, with the results and rshiny code.
I dont like the mix at the moment, results must fit the gearshifft github version, otherwise it is inconsistent. Hence, I cannot compare different gearshifft versions, where a new library has been added. I mean, I have to rerun all the benchmarks to make the results consistent with the gearshifft release.
And the commits become bloated. So if you @psteinb agree, can you create a new repo for that?

**Comment by psteinb** [comment]
Done.
https://github.com/mpicbg-scicomp/gearshifft_results

**Comment by tdd11235813** [comment]
Thank you. I cannot push the initial commit to gearshifft_results. Do I have the rights to?

**Comment by psteinb** [comment]
I'll see to it. A PR should work though.

**Comment by tdd11235813** [comment]
as long as it is empty, a fork is not possible. But I already prepared the initial commit, and I can push it directly.

**Comment by psteinb** [comment]
I added you as collaborator, please try again.

**Comment by tdd11235813** [comment]
hmm it still complains, so you have to initialize the repo first.

**Comment by tdd11235813** [comment]
nvm (there was an invite, but did not see it).

**Comment by tdd11235813** [comment]
ok, works, thank you!
