### ISSUE TITLE
travis integration of gearshifft

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft#116]
for travis integration of gearshifft you need:
- account on [Travis CI](https://travis-ci.org/)
  - will be connected to your github login
- organization access of travis to mpicbg-scicomp 
  - in travis go to your accounts page and if you cannot see your organization, then check "Review and add your authorized organizations." on the left side panel
  - you referred to github, where you, as a member, can grant access for travis to mpicbg-scicomp
- in travis on the accounts page -> organizations -> mpicbg-scicomp you can enable travis CI for gearshifft
- if it is enabled, then another commit on master is required to launch the travis build process (it looks for .travis.yml in the repo)
- after succeeded we can insert a status icon in the README.md:
```
[![Build Status](https://travis-ci.org/mpicbg-scicomp/gearshifft.svg?branch=master)](https://travis-ci.org/mpicbg-scicomp/gearshifft)
```

**Comment by psteinb** [comment]
see #125
