### ISSUE TITLE
clfft not found

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/gearshifft#117]
with 48e9da1bd1befb0d15143e815f0954818a004817 I see problems in the cmake setup to find OpenCL and/or CLFFT.
```
$ CXX=`which g++` CC=`which gcc` cmake -DCLFFT_ROOT=/home/steinbac/software/clfft/2.12.2/ -DBOOST_ROOT=/sw/apps/boost/1.63.0/ ../
#...
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY) (found version "1.2")
#...
```
I checked with cmake 3.5.2, 3.7.2 and 3.9.2 and the problem prevails.

**Comment by tdd11235813** [comment]
Have you tried using
```
export CMAKE_PREFIX_PATH=/home/steinbac/software/clfft/2.12.2/:/sw/apps/boost/1.63.0/:$CMAKE_PREFIX_PATH
```
[CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/v3.0/variable/CMAKE_PREFIX_PATH.html) is the preferred way for setting up cmake environments. ax3l drew my attention to that [here](https://github.com/mpicbg-scicomp/gearshifft/issues/104#issuecomment-315028107).

What I am confused about is that the OpenCL Version 1.2 is found, but right on the next line it complains about missing OpenCL library. Maybe you can check with `ccmake`, if OpenCL_Library is empty. If so, you have to provide the OpenCL path to cmake as well.

**Comment by tdd11235813** [comment]
my variables look like this (copied from `ccmake .` in the build dir):
```
...
OpenCL_INCLUDE_DIR               /sw/taurus/libraries/cuda/8.0.61/include
OpenCL_LIBRARY                   /usr/lib64/libOpenCL.so
```

**Comment by ax3l** [comment]
OpenCL and clFFT are now also supported in spack builds :)
https://github.com/spack/spack/pull/6441

**Comment by tdd11235813** [comment]
@psteinb can we close this issue? With the cmake refactorization this become obsolete. spack will be another part, I'll update it when we release 0.4.0.

**Comment by psteinb** [comment]
yes. let's proceed.
