### ISSUE TITLE
Kernel failure: clFFT 1D double-real transforms for 2^n, n>16, on GPU

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft#17]
clFFT Outplace_Real and Inplace_Real crash the GPU FFT kernel, if double precision is used and extent is 2^n and n>16. Powers of 3, 5 and 7 seem to be fine though. CPU does not have this issue.
This happened with clFFT 2.12.0. Probably this is a bug and persists in clFFT 2.12.1. I am going to check this.
Error message:

```
fatal error: in "ClFFT/double/131072/Inplace_Real": OpenCL error CL_INVALID_COMMAND_QUEUE [-36]
FFTGeneratedStockhamAction::compileKernels failed
FFTGeneratedStockhamAction::compileKernels failed
FFTGeneratedTransposeGCNAction::compileKernels failed
```

Also noticed, that there should be information about used clfft/cufft version in the csv header of the result files.

**Comment by tdd11235813** [comment]
I am closing this, since issues are solved.

**Comment by shuwang1** [comment]
Sorry ... what is the reason for generating this error again?  I got the exact same error message.
