### ISSUE TITLE
Separate measurement of fftw plan creation

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft#51]
It should be possible to use a different workflow for fftw, so init_forward and init_backward is called before transform routines. As of version with variadic template support in gearshifft I could handle this by a further argument indicating whether plans are reusable or not.

**Comment by psteinb** [comment]
Very good idea.

**Comment by tdd11235813** [comment]
solved as template parameter was added to gearshifft::FFT to handle plan reusability in #53
