### ISSUE TITLE
Unify interface naming style?

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft#52]
C or C++ style?
```C++
  void malloc(); // or allocate?
  size_t getAllocSize(); // or get_alloc_size?
  size_t getTransferSize();
  size_t getPlanSize();
  void init_forward(); // or initForward?
  void init_backward();
  void execute_forward(); // or executeForward?
  void execute_backward();
  template<typename THostData>                                                                                                                                             
  void upload(THostData* input);
  template<typename THostData>                                                                                                                                             
  void download(THostData* output);
  void destroy();
```
I would suggest to stick with doSomething instead of do_something ...

Edit:
`TPlan` might be the wrong name for user FFT implementation, have to find a better name.

**Comment by psteinb** [comment]
i don't like camel case as it tends to make names hard to read. I like the boost way very much
http://www.boost.org/development/requirements.html#Design_and_Programming
But in principle I don't care, it needs to be consistent ... Is there a clang-format style you use or can suggest?

**Comment by tdd11235813** [comment]
ah I see, probably you are right. I just thought the style was too "C-ish" or somehow outdated^^. 
But I agree, lowercase is more readable, so let us choose this.
uhm, I am not aware of a clang style, but for local function arguments I began to use `_variable` and for members `member_` style, what do you suggest?

**Comment by psteinb** [comment]
fine with me. I brought up clang-format as it might help us, do 
formatting automatically. unfortunately, clang-format doesn't have a 
boost style :/
