### ISSUE TITLE
Figures/Plots

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft#58]
Maybe it is better, to bundle the figures from gearshifft_publication to few pdf files located in figures/ or diagrams/.
We still could keep frontpage pictures in svg to enable comparison features, but for the mass of diagrams a pdf to group figures seems more comfortable in this repository.

Btw, I play with tikzDevice in R, since the tex output seems to require pictexwd package which I had not installed. The tikzDevice in R generates tikzpictures, but the compile process takes a while, but result is quite pleasing ...

**Comment by psteinb** [comment]
I am not following this idea very well can you please elaborate or submit a PR? I haven't tried rendering anything other than png/pdf via github. PNG might work as it is a web native format. 

What did you mean by tikzDevice?

**Comment by psteinb** [comment]
let's keep this issue open for now as it touches a very important point. I think we should ship some form of utility with gearshifft that allows users to analyze the data produced by the benchmarks straight away. As I expressed on other occassions, we could either pull in the compare R script from gearshifft_publication or use the gnuplot scripts that you have already. I am more inclined to go for gnuplot to be honest and reference the gearshifft_publication script in the README.

**Comment by tdd11235813** [comment]
this is solved by our online rshiny tool which enables interactive analysis of present data provided by the gearshifft repository.
