### ISSUE TITLE
unsupported device type

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/gearshifft#63]
I am running gearshifft on a P100 with clfft 2.12.2 using the libOpenCL.so with cuda8. I am getting 
```
Unsupported device type
```
And then gearshifft exists with a non-zero signal. I am guessing that this comes from clfft or libOpenCL.so?

**Comment by tdd11235813** [comment]
please run:
```
./gearshifft_clfft -l
```
and check if P100 is listed.
If so, then run:
```
./gearshifft_clfft -d <p>:<d> ...
```
with p and d being platform and device id.

**Comment by psteinb** [comment]
ok, thanks a bunch for the tip. I see the following:
```
"ID",0:0,"ClFFT Informations","Device","Tesla P100-PCIE-16GB","Hardware","OpenCL 1.2 CUDA","Software","367.48","OpenCL","OpenCL C 1.2 ","UsedComputeUnits","56","MaxGlobalMemSize","17066885120","clFFT","2.12.2"
"ID",0:1,"ClFFT Informations","Device","GeForce GTX TITAN X","Hardware","OpenCL 1.2 CUDA","Software","367.48","OpenCL","OpenCL C 1.2 ","UsedComputeUnits","24","MaxGlobalMemSize","12799574016","clFFT","2.12.2"
```
So the P100 is `0:0`.

**Comment by tdd11235813** [comment]
phew, ok, then you should be able to run the benchmark on P100 with:
```
./gearshifft_clfft -d 0:0 ...
```

**Comment by psteinb** [comment]
the job is running, it's looking good

**Comment by psteinb** [comment]
job went through successful. thanks for the help.
