### ISSUE TITLE
where to put the wisdom

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/gearshifft#65]
Hi, I wanted to run some fftw_wisdom benchmarks. I created the wisdom files for float and double inputs. Where do I put them now so that gearshifft can pick them up? I didn't find any hint in the docs. I'll look into the code now.

**Comment by psteinb** [comment]
got it [src/benchmark.cpp:35](https://github.com/mpicbg-scicomp/gearshifft/blob/master/src/benchmark.cpp#L35), so `../config/fftwf_wisdom.txt` etc. I'll give this a try.

**Comment by psteinb** [comment]
I created symlinks to ../config/fftwf_wisdom.txt and ../config/fftw_wisdom.txt respectively, but that also requrires me to run in repo/build or equivalent, right? mmmh, we should think about using environment variables or introduce a CLI flag (which is not a priority now).

**Comment by tdd11235813** [comment]
yeah, sorry for the inconvenience, I already wrote a small hint in #41 that this is a hardcoded thing at the moment and I wanted to make it more flexible, when it would turn out, that fftw wisdom is a required feature in gearshifft fftw implementation. I admit to be a bit too lazy to put new stuff right into the readme, I should improve that. 

Keep this open, I will implement a CLI flag later, after we submitted the paper.

**Comment by psteinb** [comment]
that makes a lot of sense. thanks

**Comment by tdd11235813** [comment]
CLI flag for wisdoms implemented. 
```
./gearshifft_fftw -h
[...]
  --rigor arg (=measure)            FFTW rigor (measure, estimate, wisdom, 
                                    patient or exhaustive)
  --wisdom_sp arg                   Wisdom file for single-precision.
  --wisdom_dp arg                   Wisdom file for double-precision.
```
so I would close this issue.
