### ISSUE TITLE
Conventions for Client Code

### ISSUE THREAD

**Issue by tdd11235813** [mpicbg-scicomp/gearshifft#68]
An upcoming pull request is going to tackle the issue of harmonized client codes.
The goal is to use consistent variable names and code parts in the client codes.
In the end this will be part of the documentation. Let's discuss that part here.

## Sizes and Number of Elements (FFT)

Variable names

```
n   := n_                 (number of input elements)
n_c := n_complex_         (number of elements in FFT(input))
s   := data_size_         (buffer size of input for FFT)
s_c := data_complex_size_ (buffer size of output of FFT(input))
```

Number of elements

```
input is real:    n_c = n_0 · … · (n_{d-1} / 2 + 1)
input is complex: n_c = n_0 · … · n_{d-1} = n
```

Data sizes in bytes

| s| transform : inplace | transform : outplace |
|--- |--- |--- |
| input : real | 2 · n_c · sizeof(real) | n · sizeof(real) |
| input : complex | n · sizeof(complex) | n · sizeof(complex) |

| s_c| transform : inplace | transform : outplace |
|--- |--- |--- |
| input : real | 0 | n_c · sizeof(complex) |
| input : complex | 0 | n_c · sizeof(complex) |

## FFT Parameters

Can be compile-time constants within the client FFT class.

| Parameter | Description |
|--- |--- |
| NDim | Number of FFT dimensions |
| TPrecision | `{float, double}` |
| IsInplace | FFT works on input buffer: input = FFT(input) |
| IsComplex | input values are in complex space |
| IsInplaceReal | `IsInplace && IsComplex==false` |
| RealType | data type for real-space |
| ComplexType | data type for complex-space |
| value_type | `value_type = IsComplex ? ComplexType : RealType` |
| Extent | `std::array<size_t,NDim>` |

**Comment by psteinb** [comment]
very good, looks good to me. please submit a PR.
Peter
