### ISSUE TITLE
Install Missing

### ISSUE THREAD

**Issue by ax3l** [mpicbg-scicomp/gearshifft#97]
Hi,

I can't run `make install` since no install targets are yet defined for the created binaries.
Can you please add such to your CMake file?

Blocks packaging: https://github.com/LLNL/spack/pull/4560

**Comment by tdd11235813** [comment]
thank you a bunch for the help and pushing gearshifft into spack :)
#98 contains a simple install target, where only the gearshifft binaries will be located. I am not sure where to place the config files which are presets for the FFT extents. Would you recommend another cmake configurable path? How to keep the default path platform independent?

**Comment by psteinb** [comment]
Indeed thanks for the addition to spack. If we wish to add the presets to the install tree, I'd say PREFIX/share/extents or something along those lines.

**Comment by ax3l** [comment]
thanks for the quick fix!

please don't forget to give the final update a new  tag, e.g. `0.2.1` or whatever you prefer.
This would allow me to start with a first working version in packaging :)

**Comment by psteinb** [comment]
yes, it's on our radar. We have 2 open PRs that are close to being 
merged. I'd love to get them in tomorrow maybe and then provide a tag 
for you.

**Comment by ax3l** [comment]
awesome, just ping me.

**Comment by ax3l** [comment]
@psteinb ping-pong :) still need a new tag of yours please :)

**Comment by tdd11235813** [comment]
sorry for delay ... I have just created a lightweight tag v0.2.1-lw, but it does not include the aforementioned PRs yet. I hope it is sufficient for the first commit to spack, otherwise I provide another pre-release for it. When we will have finished the holidays we will continue the work :D .. but please let me know if there are issues, I'll stay tuned :)
